appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: hUeuZiRkgzcKJvLNNTzAsPlsmQsrMai74HSfw62iHhlj81c7B2ojvHP2ybUtJOms1h61ksPY23ckoHi/X59Oz4opyI6K1l36cNuc9EtUI6AFliLAidL4XgUimSjxxTPLr5RZYATv6xtuca+P7Z1Y2Nj2oxEm+hRml7fOyI3nU1isBB0mA7WSJxxf8kKWUd6MEPJwpiJMzlYjCP4FqW33vpJG6iZJ92SfAR3vCCELKYc+edS3QEtvLPWWz+gWDGk3lrOuP45Wd5XgRLmtlkutwpt73QPY82ze7usljrlt2zdost8hSpKy6urj81i1NQ5v1E+ew81zCXnVt+b8C9eMaoBPRnmYPIWRe+KzxrU3Qw3WyJ6tidPyGG4xBaVinfuF3KKJck8ZPMUadxJxTVxKrjHI1b6fJQgpnYfabCPDk9Bf/Rqr5tM46f6mejzRjAjaeJZ7Cc2uyBd49RDS0+/5N8YhkcvZJWmaVO4iZzOZKJ8SAu2lRnFXbOfw3GRFl6PSQyP36s5Wm3YJXUWJTLcmgYl2Xhx0R53ORfTEOVWmH4qsGHZS8MvaeAxOxj69guwBzJRYqP8nmwUKDbguW9AkMHLkygINaFdUz0c9evmDuca4eEEmGMWuHHaGumCfg+vjVnuh/xZL7Nk1QcQEHW4iosl8vHO27wgUdpgBHKD24KU=
conda_forge_output_validation: true
